services:
  kafka-cloud:
    build:
      context: ../kafka-cloud
      dockerfile: Dockerfile
    image: kafka-cloud
    container_name: kafka-cloud-ct
    ports:
      - "8080:8080"
    depends_on:
      - nifi
    volumes:
      - ./ssl:/opt/kafka/ssl
    networks:
      - kafka-net

  nifi:
    image: apache/nifi:1.21.0
    ports:
      - "8081:8081"
    environment:
      NIFI_WEB_HTTP_PORT: 8081
    volumes:
      - ./nifi_data:/opt/nifi/nifi-current/data
      - ./ssl:/opt/nifi/nifi-current/ssl
    networks:
      - kafka-net

networks:
  kafka-net:

volumes:
  nifi_data: