#kafka
spring.kafka.bootstrap-servers=rc1a-2om888iagveq89e7.mdb.yandexcloud.net:9091,rc1a-f0magmhmcnv098vf.mdb.yandexcloud.net:9091,rc1a-qgsaqtj816v317p3.mdb.yandexcloud.net:9091
kafka.topic.name=orders

#kafka security
kafka.security.protocol=SASL_SSL
kafka.sasl.mechanism=SCRAM-SHA-512
kafka.ssl.user=${KAFKA_SSL_USER:kafka-client}
kafka.ssl.password=${KAFKA_SSL_PASSWORD:kafka-client}
kafka.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username=\"%s\" password=\"%s\";

kafka.ssl.truststore.location=${KAFKA_SSL_TRUSTSTORE_LOCATION:kafka-cloud/src/main/resources/ssl}
kafka.ssl.truststore.password=${KAFKA_SSL_TRUSTSTORE_PASSWORD:password}

#kafka schema registry
kafka.schema.registry.url=https://rc1a-2om888iagveq89e7.mdb.yandexcloud.net:443

# producer
kafka.producer.acks=all
kafka.producer.retries=3
kafka.producer.properties[min.insync.replicas]=3

# pull consumer
kafka.consumer.group.id=orders
kafka.consumer.auto.offset.reset=earliest
kafka.consumer.enable.auto.commit=false